version: "{build}"

clone_folder: c:\gopath\src\gobot.io\x\gobot

platform:
  - MinGW_x64

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go
  GOVERSION: 1.15
  TEST_EXTERNAL: 1

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...
  - go get github.com/stretchr/testify

build_script:
 - go test -v -cpu=2 .
 - go test -v -cpu=2 ./drivers/aio
 - go test -v -cpu=2 ./drivers/gpio
 - go test -v -cpu=2 ./drivers/i2c
 - go test -v -cpu=2 ./platforms/firmata/...
