version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\gobot.io\x\gobot

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

build_script:
 - go test -v -cpu=2 ./...
